# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170608_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('slug', models.CharField(default='', max_length=200)),
                ('content', models.TextField(verbose_name='Zawartość')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='compiled_content',
        ),
        migrations.AddField(
            model_name='post',
            name='raw_content',
            field=models.TextField(default='', verbose_name='Zawartość surowa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', verbose_name='Zawartość'),
        ),
    ]
