# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170609_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=10, verbose_name='Kolejność'),
        ),
    ]
