# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_page_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooltip', models.CharField(max_length=200, verbose_name='Podpis')),
                ('url', models.URLField(verbose_name='Adres linku')),
                ('image', models.ImageField(height_field=36, upload_to='', verbose_name='Ikona', width_field=36)),
                ('order', models.IntegerField(default=10, verbose_name='Kolejność')),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
