# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170609_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='images/posts', verbose_name='Główny obrazek'),
        ),
        migrations.AddField(
            model_name='post',
            name='show_title',
            field=models.BooleanField(default=True, verbose_name='Pokaż tytuł'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='images/social_links', verbose_name='Ikona'),
        ),
    ]
