# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170613_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_display_stategy',
            field=models.CharField(choices=[('cover', 'cover'), ('contain', 'contain')], default='cover', max_length=30),
        ),
    ]
