# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 23:46
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_image_display_stategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_background',
            field=colorfield.fields.ColorField(blank=True, default='#FFF', max_length=18, verbose_name='Kolor tła obrazka'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_background',
            field=colorfield.fields.ColorField(default='#000', max_length=18, verbose_name='Kolor tła tytułu'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_background_opacity',
            field=models.FloatField(default='0.5', verbose_name='Przeźroczystość tła tytułu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_display_stategy',
            field=models.CharField(choices=[('cover', 'cover'), ('contain', 'contain')], default='cover', max_length=30, verbose_name='Stategia wielkości tła'),
        ),
    ]
