# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170614_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_background',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_display_stategy',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_background_opacity',
        ),
        migrations.AlterField(
            model_name='post',
            name='title_background',
            field=models.CharField(default='rgba(0, 0, 0, 0.5)', max_length=80, verbose_name='Kolor tła tytułu'),
        ),
    ]
