# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170614_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_size',
            field=models.IntegerField(default=42, verbose_name='Wielkość tytułu (px)'),
        ),
    ]
