# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-24 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_fullwidth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/base', verbose_name='Obrazek')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image_origin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Image', verbose_name='Główny obrazek'),
            preserve_default=False,
        ),
    ]
