# Generated by Django 2.0.1 on 2018-08-12 16:45

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170624_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/categories', verbose_name='Ikonka')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.TextField(blank=True, default='5 minut', verbose_name='Czas czytania'),
        ),
        migrations.AlterField(
            model_name='post',
            name='raw_content',
            field=models.TextField(help_text='\nMarkdown editor with some special tags:</br>\n!-- makes an endash –</br>\n![text][alt](img url) makes a figure</br>\n!F[text][icon name][color without #][class (can be empty)](link)</br>\n', verbose_name='Zawartość surowa'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Category', verbose_name='Kategoria'),
        ),
    ]
